# To avoid Git src safedir error
- name: "Create cadence-web dir or change ownership to root"
  file:
    path: "{{ cadence_web_path }}"
    owner: "root"
    group: "root"
    state: directory
    recurse: yes

- name: "Download cadence-web code"
  git:
    repo: "https://github.com/uber/cadence-web"
    dest: "{{ cadence_web_path }}"
    version: "{{ cadence_web_version }}"
    force: "yes"

- name: "Change cadence-web dir ownership"
  file:
    path: "{{ cadence_web_path }}"
    owner: "{{ cadence_system_user }}"
    group: "{{ cadence_system_group }}"
    state: directory
    recurse: yes

- name: "Install nodejs packages"
  npm:
    path: "{{ cadence_web_path }}"
  become_user: "{{ cadence_system_user }}"

