---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_file_variety | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - enduro_install
    - enduro_configure
    - enduro_run

- import_tasks: preflight.yml
  tags:
    - enduro_install
    - enduro_configure
    - enduro_run

- import_tasks: install.yml
  become: true
  tags:
    - enduro_install


- import_tasks: install-cadence.yml
  become: true
  tags:
    - cadence_install

- import_tasks: install-cadence-web.yml
  become: true
  tags:
    - cadence_web_install



- import_tasks: configure.yml
  become: true
  tags:
    - enduro_configure

- name: Ensure services are enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: "{{ item }}"
    enabled: true
  with_items:
    - enduro
    - cadence
  tags:
    - enduro_run
